### ISSUE TITLE
An alternavite implementation

### ISSUE THREAD

**Issue by miguelhasse** [kekyo/CenterCLR.NamingFormatter#2]
Hi Kekyo, even though this is no longer needed with C# 6, please have a look at my solution https://gist.github.com/miguelhasse/6920437fee3e21c3844d

**Comment by kekyo** [comment]
Sorry I missed your post. Does this solution delegate to lookup by the function?
(Likely the callback form for NamingFormatter?)

I don't know how works alternative solution in C# 6? I know the string interpolation, but it's statically interpretation at the compile time. NamingFormatter is dynamic (runtime interpretation.)

**Comment by miguelhasse** [comment]
@kekyo that's exactly it, the function is used to lookup named format item values, providing runtime interpretation. It is a modified version of the original _string.Format_ implementation.

**Comment by kekyo** [comment]
Thanks your suggestion. I designed it same as your opinion how easy replacing from the "string.Format". The background is how string interporation in dynamic at using by the end user. For example, my project  RelaxVersioner's rule file contains custom format string because it can pickup the git repository metadata selectable. It uses the NamingFormatter.

https://github.com/kekyo/CenterCLR.RelaxVersioner#sample-custom-rule-set-file
